### ISSUE TITLE
Update file paths to proper slashing - not windows slashes

### ISSUE THREAD

**Issue by nhurde** [pawbyte/Game-Pencil-Engine-Editor#73]
high on tantor via discord:
I instantly got errors because you are using windows-isms like backsplashes in file paths which dont work in Mac, Linux, and other unix-likes such as FreeBSD.

Although most file paths are unix-based, some windows slashes were able to make it into the code repo.

Update so file paths work fine on all devices.

**Comment by time-killer-games** [comment]
note only one file was like this, the other errors were related to me attempting to compile with clang, but building with gcc worked fine after that one change iirc. :) I'll check what file that was now.

**Comment by nhurde** [comment]
Not super familiar with clang, so that will be an issue in itself lol.

**Comment by time-killer-games** [comment]
Clang is not really a compiler you need to support honestly, but you like permissive licneses from how I've heard you talk. GCC is GPL with a linking exception for the binaries you build with it, where as LLVM Clang is fully permissive, even the compiler itself, not just the things you build with it.
